deps(eslint-config-streamr-ts): Minor version update for `eslint` and `typescript-eslint` (#267)
Updated dependencies. There is a bug in `typescript-eslint` versions
prior v8.15:
https://github.com/typescript-eslint/typescript-eslint/pull/10339. If
`typescript-eslint` and `eslint` are used implicitly the
`eslint-config-streamr-ts` package, this update solves the following
error:
```
TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting ...
    at Object.create (.../node_modules/eslint/lib/rules/no-unused-expressions.js:75:13)
```